version: '3'
services:
  myapp:
    build: ./mqtt_server
    volumes:
      - .:/usr/src/myapp
    ports:
      - "8000:8000"

  redis:
    image: redislabs/redistimeseries
    ports:
      - "6379:6379"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"

  mqtt:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
