[package]
name = "mqtt_server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rumqttc = "0.22.0"
tokio = { version = "1", features = ["full"] }
redis = "0.21.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"